# Generated by Django 5.2.12 on 2026-05-02 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='images/profile/default/user-default-ava.jpg', null=True, upload_to=''),
        ),
    ]
