# Generated by Django 5.2.12 on 2026-05-02 08:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(code='invalid_tel_number', message='Невірне значення', regex='^(\\+?38)?(0\\d{2})\\d{3}\\d{2}\\d{2}$')], verbose_name='Номер телефону'),
        ),
    ]
