"""
Django settings for cemetery project.

Generated by 'django-admin startproject' using Django 4.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from environs import Env
import os



env = Env()
env.read_env()
#
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)
print(f"DEBUG = {DEBUG}")
# Directory of python virtual environment
# VENV_DIR = env.str("VENV_DIR")
# If True then test config is used otherwise regular config is used
IS_TEST_CONFIG = env.bool("IS_TEST_CONFIG", default=False)
print(f"IS_TEST_CONFIG = {IS_TEST_CONFIG}")


# Build paths inside the project like this: BASE_DIR / 'subdir'.
# BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = Path(__file__).resolve().parent.parent.parent
#print(f"BASE_DIR = {BASE_DIR}")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str("SECRET_KEY")


# # Vars for regular config
# DB_NAME = env.str("DB_NAME")
# DB_USER = env.str("DB_USER")
# DB_PASSWORD = env.str("DB_PASSWORD")
# DB_HOST = env.str("DB_HOST")
# DB_PORT = env.str("DB_PORT")
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
# #
# if IS_TEST_CONFIG:
#     print(f"!!! TESTS ARE RUNNING !!!")
#     DB_NAME = env.str("DB_NAME_TEST")
#     DB_USER = env.str("DB_USER_TEST")
#     DB_PASSWORD = env.str("DB_PASSWORD_TEST")
#     DB_HOST = env.str("DB_HOST_TEST")
#     DB_PORT = env.str("DB_PORT_TEST")
#     STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"

# print(f"DB_NAME = {DB_NAME}")

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")
# ALLOWED_HOSTS = [
#     '127.0.0.1',
#     '192.168.1.101',
#     #'*',
# ]

# CSRF_TRUSTED_ORIGINS = ['https://*.fly.dev']


if not DEBUG:
    # Add this if using a reverse proxy like Nginx
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # If you want to force HTTPS (optional)
    SECURE_SSL_REDIRECT = True
    APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    # Preloaded apps
    # 'jazzmin',
    #
    # Django native
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    # 'whitenoise.runserver_nostatic',
    'django.contrib.staticfiles',
    #'django.contrib.gis',
    #
    # Local
    "accounts",
    "mainapp",
    # "mainapp.apps.MainappAdminConfig",  # replaces 'django.contrib.admin'
    # "reports.apps.ReportsConfig",
    # "user_guide.apps.UserGuideConfig",
    #
    # Third-party
]


MIDDLEWARE = [
    #"debug_toolbar.middleware.DebugToolbarMiddleware",
    'django.middleware.security.SecurityMiddleware',
    # 'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # 'simple_history.middleware.HistoryRequestMiddleware',
    # 'django.middleware.locale.LocaleMiddleware',
]


ROOT_URLCONF = 'task_manager.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 'mainapp.context_processors.app_settings'
            ],
        },
    },
]

WSGI_APPLICATION = 'task_manager.wsgi.application'

AUTH_USER_MODEL = "accounts.User"


# Database--------------------------------------------------------
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
""""""
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         # 'ENGINE': 'django.contrib.gis.db.backends.postgis',
#         'NAME': DB_NAME,
#         'USER': DB_USER,
#         'PASSWORD': DB_PASSWORD,
#         'HOST': DB_HOST,
#         'PORT': DB_PORT,
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# print(f"DATABASES = {DATABASES}")

#------------------------------------------------------------------------

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'
# LANGUAGE_CODE = 'uk-UA'

TIME_ZONE = 'UTC'
# TIME_ZONE = 'EET'

USE_I18N = True

USE_TZ = True

# LANGUAGES = [
#     # ('uk', 'Ukrainian'),
#     # ('es', 'Spanish'),
#     # ('fr', 'French'),
# ]
# LOCALE_PATHS = [os.path.join(BASE_DIR, 'locale')]


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static')
]
# STATIC_ROOT = env.str("STATIC_ROOT") #os.path.join(BASE_DIR, 'assets/static')
# MEDIA_ROOT = env.str("MEDIA_ROOT") #os.path.join(BASE_DIR, 'assets/media')
# STATICFILES_STORAGE is initialized at the top

# This production code might break development mode, so we check whether we're in DEBUG mode
# if not DEBUG:
#     # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
#     #STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
#     # Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
#     # and renames the files with unique names for each version to support long-term caching
#     STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


INTERNAL_IPS = [
    # ...
    "127.0.0.1",
    # ...
]


# GDAL_LIBRARY_PATH = VENV_DIR + 'Lib/site-packages/osgeo/gdal304.dll'
# GEOS_LIBRARY_PATH = VENV_DIR + 'Lib/site-packages/osgeo/geos_c.dll'

# SIMPLE_HISTORY_REVERT_DISABLED = True


# Custom settings -------------------------------------------------------

# # bootstrap files should lie in static folder
# BOOTSTRAP_PATH_FILE_CSS = 'bootstrap-5.3.1-dist/css/bootstrap.min.css'
# BOOTSTRAP_PATH_FILE_JS = 'bootstrap-5.3.1-dist/js/bootstrap.bundle.min.js'

# #jquery
# JQUERY_PATH_FILE = 'jquery-3.7.1/jquery-3.7.1.min.js'



# COMPANY_NAME = env.str("COMPANY_NAME")
# COMPANY_SITE_URL = env.str("COMPANY_SITE_URL")



# COMPANY_DEFAULT_GEO_LOCATION = {
#         'LAT': env.float("COMPANY_DEFAULT_GEO_LOCATION_LAT"),
#         'LON': env.float("COMPANY_DEFAULT_GEO_LOCATION_LON"),
#         'ZOOM': env.float("COMPANY_DEFAULT_GEO_LOCATION_ZOOM"),
#         'MAXZOOM': env.float("COMPANY_DEFAULT_GEO_LOCATION_MAXZOOM"),
#     }

# IS_CEMETERY_AREA_IN_USE = env.bool("IS_CEMETERY_AREA_IN_USE")

# # admin url 1st part
# ADMIN_URL1 = "cemadm"

#------------------------------------------------------------------------



